/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CopiableText: typeof import('./src/@core/components/CopiableText.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NewOrder: typeof import('./src/components/NewOrder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stepper: typeof import('./src/@core/components/Stepper.vue')['default']
    StepProgress: typeof import('./src/@core/components/StepProgress.vue')['default']
    Temp: typeof import('./src/components/temp.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
